{
 "PRed": [
  {
   "PR": {
    "number": 1,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python38"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/359519625.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "0.8"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/499710431.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "pypy"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/503046395.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 2,
    "migrator_version": 0,
    "name": "python39"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/686140473.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "0.9"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/836325495.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python310"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad": false,
 "pinning_version": "2022.01.29.15.10.18",
 "pre_pr_migrator_attempts": {
  "pypy38": 6,
  "python311": 876,
  "python312": 4
 },
 "pre_pr_migrator_status": {
  "pypy38": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/6379735003\">bot CI job</a>): main: ['linux_64_python3.10.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.3-py_0 requires rjsmin 1.0.12, but none of the providers can be installed\\n', 'linux_64_python3.11.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.2-py_1 requires rjsmin 1.0.12, but none of the providers can be installed\\n', 'linux_64_python3.9.____73_pypy: Encountered problems while solving:\\n  - package django_compressor-2.3-py_0 requires rjsmin 1.0.12, but none of the providers can be installed\\n', 'osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.3-py_0 requires rjsmin 1.0.12, but none of the providers can be installed\\n', 'osx_64_python3.11.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.2-py_1 requires rjsmin 1.0.12, but none of the providers can be installed\\n', 'osx_64_python3.9.____73_pypy: Encountered problems while solving:\\n  - package django_compressor-2.3-py_0 requires rjsmin 1.0.12, but none of the providers can be installed\\n', 'win_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides vc 9.* needed by python-2.7.12-0\\n', 'win_64_python3.11.____cpython: Encountered problems while solving:\\n  - nothing provides vc 9.* needed by python-2.7.12-0\\n', 'win_64_python3.9.____73_pypy: Encountered problems while solving:\\n  - nothing provides vc 9.* needed by python-2.7.12-0\\n']",
  "python311": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/6270761630\">bot CI job</a>): main: ['linux_64_python3.10.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.3-py_0 requires rjsmin 1.0.12, but none of the providers can be installed\\n', 'linux_64_python3.11.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.2-py_1 requires rjsmin 1.0.12, but none of the providers can be installed\\n', 'osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.3-py_0 requires rjsmin 1.0.12, but none of the providers can be installed\\n', 'osx_64_python3.11.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.2-py_1 requires rjsmin 1.0.12, but none of the providers can be installed\\n', 'win_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides vc 9.* needed by python-2.7.12-0\\n', 'win_64_python3.11.____cpython: Encountered problems while solving:\\n  - nothing provides vc 9.* needed by python-2.7.12-0\\n']",
  "python312": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/6385036959\">bot CI job</a>): main: ['linux_64_python3.10.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.2-py_1 requires rjsmin 1.0.12, but none of the providers can be installed', 'linux_64_python3.11.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.2-py_1 requires rjsmin 1.0.12, but none of the providers can be installed', 'linux_64_python3.12.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.2-py_1 requires rjsmin 1.0.12, but none of the providers can be installed', 'osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.2-py_1 requires rjsmin 1.0.12, but none of the providers can be installed', 'osx_64_python3.11.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.2-py_1 requires rjsmin 1.0.12, but none of the providers can be installed', 'osx_64_python3.12.____cpython: Encountered problems while solving:\\n  - package django_compressor-2.2-py_1 requires rjsmin 1.0.12, but none of the providers can be installed', 'win_64_python3.10.____cpython: Encountered problems while solving:\\n  - nothing provides vc 9.* needed by python-2.7.12-0', 'win_64_python3.11.____cpython: Encountered problems while solving:\\n  - nothing provides vc 9.* needed by python-2.7.12-0', 'win_64_python3.12.____cpython: Encountered problems while solving:\\n  - nothing provides vc 9.* needed by python-2.7.12-0']"
 },
 "smithy_version": "3.16.2"
}