{
 "PRed": [
  {
   "PR": {
    "number": 2,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python311"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 3,
    "state": "closed"
   },
   "data": {
    "bot_rerun": 1679924224.1623476,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "4.0.1.1"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 6,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "4.0.1.1"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 7,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "4.0.1.2"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 10,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "4.0.1.3"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": 11,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "4.0.3"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  }
 ],
 "bad": false,
 "pinning_version": "2023.04.28.23.49.10",
 "pre_pr_migrator_attempts": {
  "pypy38": 107
 },
 "pre_pr_migrator_status": {
  "pypy38": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/5507201419\">bot CI job</a>): main: ['linux_64_python3.8.____73_pypyqt5: Encountered problems while solving:\\n  - package pyside2-5.13.2-py38h3b90aee_2 requires qt >=5.12.9,<5.13.0a0, but none of the providers can be installed', 'linux_64_python3.8.____73_pypyqt6: Encountered problems while solving:\\n  - package pyside6-6.5.0-py38h0e207de_2 requires python_abi 3.8.* *_cp38, but none of the providers can be installed', 'linux_64_python3.9.____73_pypyqt5: Encountered problems while solving:\\n  - package pyside2-5.13.2-py39h9c294d1_3 requires qt >=5.12.9,<5.13.0a0, but none of the providers can be installed', 'linux_64_python3.9.____73_pypyqt6: Encountered problems while solving:\\n  - package qt6-advanced-docking-system-4.0.3-h254bb04_0 requires qt6-main >=6.4.3,<6.5.0a0, but none of the providers can be installed', 'osx_64_python3.8.____73_pypyqt5: Encountered problems while solving:\\n  - package pyside2-5.13.2-py38h5258bd1_2 requires qt >=5.12.9,<5.13.0a0, but none of the providers can be installed', 'osx_64_python3.8.____73_pypyqt6: Encountered problems while solving:\\n  - package pyside6-6.4.0-py310h2337c12_0 requires python >=3.10,<3.11.0a0, but none of the providers can be installed', 'osx_64_python3.9.____73_pypyqt5: Encountered problems while solving:\\n  - package pyside2-5.13.2-py39h717a4ca_3 requires qt >=5.12.9,<5.13.0a0, but none of the providers can be installed', 'osx_64_python3.9.____73_pypyqt6: Encountered problems while solving:\\n  - package pyside6-6.4.0-py310h2337c12_0 requires python >=3.10,<3.11.0a0, but none of the providers can be installed', 'win_64_python3.8.____73_pypyqt5: Encountered problems while solving:\\n  - nothing provides vc 9 needed by pyside2-2.0.0.dev0-py27_vc9_0', 'win_64_python3.8.____73_pypyqt6: Encountered problems while solving:\\n  - package qt6-advanced-docking-system-4.0.3-hef519ce_0 requires qt6-main >=6.4.3,<6.5.0a0, but none of the providers can be installed', 'win_64_python3.9.____73_pypyqt5: Encountered problems while solving:\\n  - nothing provides vc 9 needed by pyside2-2.0.0.dev0-py27_vc9_0', 'win_64_python3.9.____73_pypyqt6: Encountered problems while solving:\\n  - package qt6-advanced-docking-system-4.0.3-hef519ce_0 requires qt6-main >=6.4.3,<6.5.0a0, but none of the providers can be installed']"
 },
 "smithy_version": "3.23.1"
}