{
  "done": [
    "libspatialite",
    "pyproj",
    "geotiff",
    "gdal",
    "pygplates",
    "postgis",
    "mapserver",
    "paraview"
  ],
  "in-pr": [
    "magics-metview-batch",
    "rasterio",
    "magics",
    "r-proj4",
    "fimex",
    "vtk",
    "magics-metview"
  ],
  "awaiting-pr": [],
  "not-solvable": [
    "r-terra",
    "r-sf",
    "r-rgdal",
    "r-gdalcubes",
    "pynio",
    "ncl"
  ],
  "awaiting-parents": [
    "r-lwgeom",
    "geowombat",
    "cdo",
    "r-gribr",
    "visan"
  ],
  "bot-error": [
    "qgis"
  ],
  "_feedstock_status": {
    "cdo": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "gdal": {
      "num_descendants": 13,
      "immediate_children": [
        "geowombat",
        "mapserver",
        "ncl",
        "postgis",
        "pygplates",
        "pynio",
        "qgis",
        "r-gdalcubes",
        "r-rgdal",
        "r-sf",
        "r-terra",
        "rasterio"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/gdal-feedstock/pull/744",
      "pr_status": "unknown"
    },
    "geotiff": {
      "num_descendants": 14,
      "immediate_children": [
        "gdal",
        "qgis"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/geotiff-feedstock/pull/54",
      "pr_status": "unknown"
    },
    "libspatialite": {
      "num_descendants": 14,
      "immediate_children": [
        "gdal",
        "qgis"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/libspatialite-feedstock/pull/93",
      "pr_status": "unknown"
    },
    "magics": {
      "num_descendants": 1,
      "immediate_children": [
        "cdo"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/magics-feedstock/pull/121",
      "pr_status": "unstable"
    },
    "ncl": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4701887076\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - package libgdal-3.6.3-h0e7c1b1_3 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'osx_64_: Encountered problems while solving:\\n  - package libgdal-3.6.3-h32fa94e_6 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'osx_arm64_: Encountered problems while solving:\\n  - package libgdal-3.6.3-h0a7289d_7 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n']"
    },
    "paraview": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/paraview-feedstock/pull/181",
      "pr_status": "unknown"
    },
    "postgis": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/postgis-feedstock/pull/93",
      "pr_status": "unknown"
    },
    "pynio": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4700797730\">bot CI job</a>): main: ['linux_64_numpy1.21python3.10.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h0e7c1b1_3 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'linux_64_numpy1.21python3.8.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h0e7c1b1_3 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'linux_64_numpy1.21python3.9.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h0e7c1b1_3 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'linux_64_numpy1.23python3.11.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h0e7c1b1_3 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'osx_64_numpy1.21python3.10.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h32fa94e_6 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'osx_64_numpy1.21python3.8.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h32fa94e_6 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'osx_64_numpy1.21python3.9.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h32fa94e_6 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'osx_64_numpy1.23python3.11.____cpython: Encountered problems while solving:\\n  - package libgdal-3.6.3-h32fa94e_6 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n']"
    },
    "pyproj": {
      "num_descendants": 2,
      "immediate_children": [
        "geowombat",
        "qgis"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/pyproj-feedstock/pull/135",
      "pr_status": "unknown"
    },
    "qgis": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4612719562\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 252, in run\n    migrator.run_post_piggyback_migrations(recipe_dir, feedstock_ctx.attrs, **kwargs)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migrators/core.py\", line 290, in run_post_piggyback_migrations\n    mini_migrator.migrate(recipe_dir, attrs, **kwargs)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migrators/cross_compile.py\", line 386, in migrate\n    config = yaml_safe_load(f)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 90, in yaml_safe_load\n    return ruamel.yaml.YAML(typ=\"safe\", pure=True).load(stream)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 131, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 674, in construct_yaml_map\n    value = self.construct_mapping(node)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 445, in construct_mapping\n    return BaseConstructor.construct_mapping(self, node, deep=deep)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 263, in construct_mapping\n    if self.check_mapping_key(node, key_node, mapping, key, value):\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 294, in check_mapping_key\n    raise DuplicateKeyError(*args)\nruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping\n  in \"../conda-forge.yml\", line 1, column 1\nfound duplicate key \"provider\" with value \"{}\" (original value: \"{}\")\n  in \"../conda-forge.yml\", line 24, column 1\n\nTo suppress this check see:\n    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\n\n"
    },
    "r-proj4": {
      "num_descendants": 1,
      "immediate_children": [
        "r-gribr"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/r-proj4-feedstock/pull/40",
      "pr_status": "unstable"
    },
    "r-rgdal": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4701887076\">bot CI job</a>): main: ['linux_64_r_base4.1: Encountered problems while solving:\\n  - package r-base-4.1.0-h9e01966_0 requires jpeg >=9d,<10a, but none of the providers can be installed\\n', 'osx_64_r_base4.1: Encountered problems while solving:\\n  - package r-base-4.1.0-h410e534_2 requires jpeg >=9d,<10a, but none of the providers can be installed\\n']"
    },
    "r-sf": {
      "num_descendants": 1,
      "immediate_children": [
        "r-lwgeom"
      ],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4701887076\">bot CI job</a>): main: ['linux_64_r_base4.1: Encountered problems while solving:\\n  - package r-base-4.1.0-h9e01966_0 requires jpeg >=9d,<10a, but none of the providers can be installed\\n', 'linux_aarch64_r_base4.1: Encountered problems while solving:\\n  - package r-base-4.1.0-h2889e3b_2 requires jpeg >=9d,<10a, but none of the providers can be installed\\n', 'linux_ppc64le_r_base4.1: Encountered problems while solving:\\n  - package r-base-4.1.0-h0f82cec_0 requires jpeg >=9d,<10a, but none of the providers can be installed\\n', 'osx_64_r_base4.1: Encountered problems while solving:\\n  - package r-base-4.1.0-h410e534_2 requires jpeg >=9d,<10a, but none of the providers can be installed\\n']"
    },
    "rasterio": {
      "num_descendants": 1,
      "immediate_children": [
        "geowombat"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/rasterio-feedstock/pull/264",
      "pr_status": "unstable"
    },
    "vtk": {
      "num_descendants": 1,
      "immediate_children": [
        "visan"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/vtk-feedstock/pull/292",
      "pr_status": "clean"
    },
    "r-gribr": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "r-lwgeom": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "magics-metview": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/magics-metview-feedstock/pull/64",
      "pr_status": "unstable"
    },
    "magics-metview-batch": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/magics-metview-batch-feedstock/pull/55",
      "pr_status": "unstable"
    },
    "geowombat": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "fimex": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/fimex-feedstock/pull/55",
      "pr_status": "unstable"
    },
    "r-gdalcubes": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4701887076\">bot CI job</a>): main: ['linux_64_r_base4.1: Encountered problems while solving:\\n  - package r-base-4.1.0-h9e01966_0 requires jpeg >=9d,<10a, but none of the providers can be installed\\n', 'linux_64_r_base4.2: Encountered problems while solving:\\n  - package libgdal-3.6.3-h0e7c1b1_3 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n', 'osx_64_r_base4.1: Encountered problems while solving:\\n  - package r-base-4.1.0-h410e534_2 requires jpeg >=9d,<10a, but none of the providers can be installed\\n', 'osx_64_r_base4.2: Encountered problems while solving:\\n  - package libgdal-3.6.3-h32fa94e_6 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed\\n']"
    },
    "r-terra": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4700797730\">bot CI job</a>): main: ['linux_64_r_base4.1: Encountered problems while solving:\\n  - package libgdal-3.6.3-h0e7c1b1_3 requires geos >=3.11.2,<3.11.3.0a0, but none of the providers can be installed\\n', 'linux_64_r_base4.2: Encountered problems while solving:\\n  - package libgdal-3.6.3-h0e7c1b1_3 requires geos >=3.11.2,<3.11.3.0a0, but none of the providers can be installed\\n', 'linux_aarch64_r_base4.1: Encountered problems while solving:\\n  - package libgdal-3.6.3-h09f3c6d_3 requires geos >=3.11.2,<3.11.3.0a0, but none of the providers can be installed\\n', 'linux_aarch64_r_base4.2: Encountered problems while solving:\\n  - package libgdal-3.6.3-h09f3c6d_3 requires geos >=3.11.2,<3.11.3.0a0, but none of the providers can be installed\\n', 'linux_ppc64le_r_base4.1: Encountered problems while solving:\\n  - package libgdal-3.6.3-h10fbef7_7 requires geos >=3.11.2,<3.11.3.0a0, but none of the providers can be installed\\n', 'linux_ppc64le_r_base4.2: Encountered problems while solving:\\n  - package libgdal-3.6.3-h10fbef7_7 requires geos >=3.11.2,<3.11.3.0a0, but none of the providers can be installed\\n', 'osx_64_r_base4.1: Encountered problems while solving:\\n  - package libgdal-3.6.3-h32fa94e_6 requires geos >=3.11.2,<3.11.3.0a0, but none of the providers can be installed\\n', 'osx_64_r_base4.2: Encountered problems while solving:\\n  - package libgdal-3.6.3-h32fa94e_6 requires geos >=3.11.2,<3.11.3.0a0, but none of the providers can be installed\\n']"
    },
    "visan": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "mapserver": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/mapserver-feedstock/pull/25",
      "pr_status": "unknown"
    },
    "pygplates": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/pygplates-feedstock/pull/5",
      "pr_status": "unknown"
    }
  }
}