{
  "done": [
    "paraview",
    "libspatialite",
    "pyproj",
    "geotiff",
    "gdal",
    "pygplates",
    "postgis",
    "mapserver"
  ],
  "in-pr": [
    "magics-metview-batch",
    "magics-metview",
    "r-proj4",
    "magics",
    "fimex",
    "vtk",
    "rasterio"
  ],
  "awaiting-pr": [],
  "not-solvable": [],
  "awaiting-parents": [
    "r-gribr",
    "cdo",
    "visan",
    "r-lwgeom",
    "geowombat"
  ],
  "bot-error": [
    "r-terra",
    "r-sf",
    "r-rgdal",
    "r-gdalcubes",
    "qgis",
    "pynio",
    "ncl"
  ],
  "_feedstock_status": {
    "cdo": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "gdal": {
      "num_descendants": 13,
      "immediate_children": [
        "geowombat",
        "mapserver",
        "ncl",
        "postgis",
        "pygplates",
        "pynio",
        "qgis",
        "r-gdalcubes",
        "r-rgdal",
        "r-sf",
        "r-terra",
        "rasterio"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/gdal-feedstock/pull/744",
      "pr_status": "unknown"
    },
    "geotiff": {
      "num_descendants": 14,
      "immediate_children": [
        "gdal",
        "qgis"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/geotiff-feedstock/pull/54",
      "pr_status": "unknown"
    },
    "libspatialite": {
      "num_descendants": 14,
      "immediate_children": [
        "gdal",
        "qgis"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/libspatialite-feedstock/pull/93",
      "pr_status": "unknown"
    },
    "magics": {
      "num_descendants": 1,
      "immediate_children": [
        "cdo"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/magics-feedstock/pull/121",
      "pr_status": "unstable"
    },
    "ncl": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4626268180\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 348, in run\n    solvable, errors, _ = is_recipe_solvable(\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/conda_forge_feedstock_check_solvable/mamba_solver.py\", line 652, in is_recipe_solvable\n    res = parent_conn.recv()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/multiprocessing/connection.py\", line 251, in recv\n    return _ForkingPickler.loads(buf.getbuffer())\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/requests/exceptions.py\", line 41, in __init__\n    CompatJSONDecodeError.__init__(self, *args)\nTypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'\n"
    },
    "paraview": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/paraview-feedstock/pull/181",
      "pr_status": "unknown"
    },
    "postgis": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/postgis-feedstock/pull/93",
      "pr_status": "unknown"
    },
    "pynio": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4626268180\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 348, in run\n    solvable, errors, _ = is_recipe_solvable(\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/conda_forge_feedstock_check_solvable/mamba_solver.py\", line 652, in is_recipe_solvable\n    res = parent_conn.recv()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/multiprocessing/connection.py\", line 251, in recv\n    return _ForkingPickler.loads(buf.getbuffer())\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/requests/exceptions.py\", line 41, in __init__\n    CompatJSONDecodeError.__init__(self, *args)\nTypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'\n"
    },
    "pyproj": {
      "num_descendants": 2,
      "immediate_children": [
        "geowombat",
        "qgis"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/pyproj-feedstock/pull/135",
      "pr_status": "unknown"
    },
    "qgis": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4612719562\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 252, in run\n    migrator.run_post_piggyback_migrations(recipe_dir, feedstock_ctx.attrs, **kwargs)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migrators/core.py\", line 290, in run_post_piggyback_migrations\n    mini_migrator.migrate(recipe_dir, attrs, **kwargs)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migrators/cross_compile.py\", line 386, in migrate\n    config = yaml_safe_load(f)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 90, in yaml_safe_load\n    return ruamel.yaml.YAML(typ=\"safe\", pure=True).load(stream)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 131, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 674, in construct_yaml_map\n    value = self.construct_mapping(node)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 445, in construct_mapping\n    return BaseConstructor.construct_mapping(self, node, deep=deep)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 263, in construct_mapping\n    if self.check_mapping_key(node, key_node, mapping, key, value):\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 294, in check_mapping_key\n    raise DuplicateKeyError(*args)\nruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping\n  in \"../conda-forge.yml\", line 1, column 1\nfound duplicate key \"provider\" with value \"{}\" (original value: \"{}\")\n  in \"../conda-forge.yml\", line 24, column 1\n\nTo suppress this check see:\n    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\n\n"
    },
    "r-proj4": {
      "num_descendants": 1,
      "immediate_children": [
        "r-gribr"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/r-proj4-feedstock/pull/40",
      "pr_status": "unstable"
    },
    "r-rgdal": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4626877581\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 348, in run\n    solvable, errors, _ = is_recipe_solvable(\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/conda_forge_feedstock_check_solvable/mamba_solver.py\", line 652, in is_recipe_solvable\n    res = parent_conn.recv()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/multiprocessing/connection.py\", line 251, in recv\n    return _ForkingPickler.loads(buf.getbuffer())\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/requests/exceptions.py\", line 41, in __init__\n    CompatJSONDecodeError.__init__(self, *args)\nTypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'\n"
    },
    "r-sf": {
      "num_descendants": 1,
      "immediate_children": [
        "r-lwgeom"
      ],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4626877581\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 348, in run\n    solvable, errors, _ = is_recipe_solvable(\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/conda_forge_feedstock_check_solvable/mamba_solver.py\", line 652, in is_recipe_solvable\n    res = parent_conn.recv()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/multiprocessing/connection.py\", line 251, in recv\n    return _ForkingPickler.loads(buf.getbuffer())\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/requests/exceptions.py\", line 41, in __init__\n    CompatJSONDecodeError.__init__(self, *args)\nTypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'\n"
    },
    "rasterio": {
      "num_descendants": 1,
      "immediate_children": [
        "geowombat"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/rasterio-feedstock/pull/264",
      "pr_status": "unstable"
    },
    "vtk": {
      "num_descendants": 1,
      "immediate_children": [
        "visan"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/vtk-feedstock/pull/292",
      "pr_status": "clean"
    },
    "r-gribr": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "r-lwgeom": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "magics-metview": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/magics-metview-feedstock/pull/64",
      "pr_status": "unstable"
    },
    "magics-metview-batch": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/magics-metview-batch-feedstock/pull/55",
      "pr_status": "unstable"
    },
    "geowombat": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "fimex": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/fimex-feedstock/pull/55",
      "pr_status": "unstable"
    },
    "r-gdalcubes": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4626877581\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 348, in run\n    solvable, errors, _ = is_recipe_solvable(\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/conda_forge_feedstock_check_solvable/mamba_solver.py\", line 652, in is_recipe_solvable\n    res = parent_conn.recv()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/multiprocessing/connection.py\", line 251, in recv\n    return _ForkingPickler.loads(buf.getbuffer())\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/requests/exceptions.py\", line 41, in __init__\n    CompatJSONDecodeError.__init__(self, *args)\nTypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'\n"
    },
    "r-terra": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4626877581\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 348, in run\n    solvable, errors, _ = is_recipe_solvable(\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/conda_forge_feedstock_check_solvable/mamba_solver.py\", line 652, in is_recipe_solvable\n    res = parent_conn.recv()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/multiprocessing/connection.py\", line 251, in recv\n    return _ForkingPickler.loads(buf.getbuffer())\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/requests/exceptions.py\", line 41, in __init__\n    CompatJSONDecodeError.__init__(self, *args)\nTypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'\n"
    },
    "visan": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    },
    "mapserver": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/mapserver-feedstock/pull/25",
      "pr_status": "unknown"
    },
    "pygplates": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/pygplates-feedstock/pull/5",
      "pr_status": "unknown"
    }
  }
}